name: build

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 14

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Check Formatting
        run: npm run prettier
