name: build

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 14

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check Formatting
        run: yarn prettier
